### ISSUE TITLE
Problem with the Shisha Script

### ISSUE THREAD

**Issue by bylickilabs** [madskgg/esx_hookah#1]
Hello
I have a problem with the script! Instead of the hose for the shisha, a chair is spawned. The question is why?

Please help

![screenshot](https://github.com/madskgg/esx_hookah/assets/109308073/faca5a01-9c67-4e74-af81-91d916c23f94)
![screenshot2](https://github.com/madskgg/esx_hookah/assets/109308073/7b0e7cc0-d1aa-4943-868d-6f697034c92c)

**Comment by bylickilabs** [comment]
![screenshot](https://github.com/madskgg/esx_hookah/assets/109308073/942b9443-5a8c-4a95-9439-1cfa94ea0078)

**Comment by madskgg** [comment]
@bylickilabs You need the correct streamable file in order for the hose to appear. I haven't worked on esx_hookah for a while now. Let me check if I have the correct prop saved somewhere

**Comment by bylickilabs** [comment]
@madskgg Thank you, I'll wait.

**Comment by madskgg** [comment]
[v_corp_lngestoolfd.zip](https://github.com/madskgg/esx_hookah/files/13465092/v_corp_lngestoolfd.zip)
@bylickilabs I think it's this one, check it out

**Comment by bylickilabs** [comment]
This File copy In the MLO?

**Comment by madskgg** [comment]
Yes copy and paste it there (if there is another ydr file with the same name, replace it with this one)

**Comment by bylickilabs** [comment]
oh okay, I have before you sended your File no v_corp_lngestoolfd.ydr. I Try

**Comment by bylickilabs** [comment]
With the paste your File, The Script is now without Function. 

One Moment, i have found the problem with the get shared Objects.
I'll just rewrite it!

**Comment by bylickilabs** [comment]
@madskgg The Script is now full Functionally für the newest ESX Version. 

I will archive the revised script and then send it to you! Thank you

**Comment by bylickilabs** [comment]
[esx_hookah.zip](https://github.com/madskgg/esx_hookah/files/13465121/esx_hookah.zip)
